 
name: Unit Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.3.0
      
      - name: Run Build Scripts
        run: bash scripts/run-tests.sh

      - name: Upload Test Output
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: tests/out
