 
name: Unit Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
      - uses: actions/checkout@v3
      
      - name: Run Build Scripts
        run: bash scripts/run-tests.sh